services:
  mihomo:
    image: haeho7/docker-images:mihomo
    container_name: mihomo
    restart: unless-stopped
    network_mode: host
    #pid: host
    #ipc: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Taipei
      USE_IPTABLES_NFT_BACKEND: 0
    volumes:
      - ./mihomo-data:/etc/mihomo
    command: -d /etc/mihomo

  # dashboard
  metacubexd:
    image: haeho7/docker-images:metacubexd
    container_name: metacubexd
    restart: unless-stopped
    network_mode: host
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Taipei
      METACUBEXD_PORT: 9091
