services:
  mihomo:
    image: haeho7/docker-images:mihomo
    container_name: mihomo
    restart: unless-stopped
    network_mode: host
    #pid: host
    #ipc: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Taipei
      USE_IPTABLES_NFT_BACKEND: 0
    volumes:
      - ./mihomo-data:/etc/mihomo
    command: -d /etc/mihomo

  # dashboard
  metacubexd:
    image: ghcr.io/metacubex/metacubexd
    container_name: metacubexd
    restart: unless-stopped
    network_mode: bridge
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Taipei
      DEFAULT_BACKEND_URL: http://192.168.1.1:9090
    ports:
      - 9091:80
